name: Notify on Release

on:
    release:
        types: [published]

jobs: 
    slack-message:
        runs-on: ubuntu-latest
        steps:
            - name: Slack Message
              run: |
                echo "Need to add the curl command to send messageds"